# Generated by Django 3.2.9 on 2021-11-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bought_currency_fee',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sold_currency_amount',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sold_currency_fee',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
