# Generated by Django 3.2.9 on 2021-11-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20211115_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bought_currency_fee',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sold_currency_fee',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19),
        ),
    ]
