# Generated by Django 3.2.9 on 2021-11-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20211117_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
